name: 'Terraform'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  terraform-plan:
    uses: szirmaibence98/templates/.github/workflows/terraform-plan.yml@main
    with:
      environment_name: 'dev'
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
