name: 'Terraform'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  terrafrom-plan:
    uses: szirmaibence98/templates/.github/workflows/terrafrom-plan.yml@main
    with:
      environment_name: 'dev'
